import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import StoreProvider from "../providers/StoreProvider";
import { AuthProvider } from "../providers/AuthProvider";
<<<<<<< HEAD
// import Header from "@/components/Header";
=======
// import Navbar from "@/components/Navbar";
>>>>>>> 6bb64c23b1ae9991acf2fab6fec355fb67c2f838

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          {" "}
          <AuthProvider>
<<<<<<< HEAD
            <Header/>
=======
            {/* <Navbar /> */}
>>>>>>> 6bb64c23b1ae9991acf2fab6fec355fb67c2f838
            {children}
            <Footer />
          </AuthProvider>{" "}
        </StoreProvider>
      </body>
    </html>
  );
}
